### ISSUE TITLE
Run-time error "5"

### ISSUE THREAD

**Issue by zhangpeng0610** [analyticsinmotion/add-chatgpt-to-microsoft-word#2]
![image](https://user-images.githubusercontent.com/63859833/218265485-759248bd-3f7a-47d8-a23c-83dc58a072ad.png)

![image](https://user-images.githubusercontent.com/63859833/218265541-3e8bc906-5b84-4f5e-a785-ee2090f4f3ae.png)

**Comment by rossarmstrong** [comment]
Hi @zhangpeng0610, thank you for submitting this issue. The Run-time Error 5 response probably gives the wrong impression about the underlying issue. It is essentially caused when ChatGPT is at capacity and its servers cannot respond your request at that time. To assist users of this project, we have added some simple error handling for this issue. Moving forward, when this situation occurs an Alert Message will display on the screen rather than an error message from Microsoft Visual Basic like you saw. The best thing to do after that is wait a minute and try your request again.

**Comment by rossarmstrong** [comment]
This issue has been fixed so will be closed
